config/routes.rb
Rails.application.routes.draw do
  resources :clients do
    post :create_payment, :on => :collection
  end
  match '/payments/search', to:'clients#admin', constraints: { subdomain: 'admin' }, via: [:get]
  match '/payments/search', to: 'clients#index', constraints: { subdomain: '/.+/' }, via: [:get]
  resources :payments do
    collection { post :search, to: 'clients#admin' }
  end

  match '/', to: 'clients#index', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
  match '/', to: 'clients#admin', constraints: { subdomain: 'admin' }, via: [:get]
  match '/', to: 'clients#show', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]
  match '/success', to: 'clients#index', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
  match '/success', to: 'clients#success', constraints: { subdomain: /.+/ }, via: [:post]
  match '/success', to: 'clients#index', constraints: { subdomain: /.+/ }, via: [:get, :put, :patch, :delete]
  root to: 'clients#index', subdomain: 'www', constraints: {subdomain: '/.+/'}, via: [:get]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :location
  has_many :payments

end

app/models/location.rb
class Location < ApplicationRecord
	has_many :clients
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :client
  has_one :payment_detail
  has_one :location, :through => :client
  #attr_accessible :defendent_name, :citation_number,  :email, :address, :phone_number, :amount, :convenience_fee, :total_amount, :isPaid, :client
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
  belongs_to :payment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :get_client

def payment_params
    params.require(:payment).permit(:defendent_name, :citation_number,  :email, :address, :phone_number, :amount, :convenience_fee, :total_amount, :isPaid, :client_id)
  end
private
  def get_client

    clients = Client.where(subdomain: request.subdomain)

    if clients.count > 0
      @client = clients.first
    elsif request.subdomain != 'www'
    	redirect_to root_url(subdomain: 'www')
    end
  end
end

app/controllers/clients_controller.rb
  class ClientsController < ApplicationController
   skip_before_filter :verify_authenticity_token, :only => [:success]

  def index
    @clients = Client.all
  end

  def show
    @payment = Payment.new
  end

  def create_payment
    @payment = Payment.new(payment_params)
    @payment.save
  end


  def admin
    @search = Payment.search(params[:q])
    @payments = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  def success
    @defendentName = params["defendantName"]
    @citationNumber = params["citationNo"]
    @address = params["address"]
    @phoneNumber = params["phoneNumber"]
    @email = params["email"]
    @amount = params["amount"]
    @convenienceFee = params["convenienceFee"]
  	@TotalAmt = params["TotalAmt"]
    @new_payment = Payment.new
    @new_payment.defendent_name = params["defendantName"]
    @new_payment.citation_number = params["citationNo"]
    @new_payment.email = params["email"]
    @new_payment.address = params["address"]
    @new_payment.phone_number = params["phoneNumber"]
    @new_payment.amount = params["amount"]
    @new_payment.convenience_fee = params["convenienceFee"]
    @new_payment.total_amount = params["r_AuthorizedAmount"]
    @new_payment.payment_date = Date.strptime(params["TransDate"], "%m/%d/%Y")
    @new_payment.client = @client
    @new_payment_details = PaymentDetail.new
    @new_payment_details.transaction_date = Date.strptime(params["TransDate"], "%m/%d/%Y")
    @new_payment_details.last_four_digits = params["r_LastFour"]
    @new_payment_details.card_type = params["r_CardType"]
    @new_payment_details.authorized_amount = params["r_AuthorizedAmount"]
    @new_payment.save
    @new_payment_details.payment = @new_payment
    @new_payment_details.save

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, type)
  new_object = f.object.send "build_#{type}"
  id = "new_#{type}"
  fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
    render(type.to_s + "_fields", f: builder)
  end
  link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
  <div class="row col-md-4">
  	<%= a.attribute_select({associations: [:client, :location]}, :class => 'form-control' )  %>
  </div>
  <% end %>
  <div class="row col-md-4">
  <%= f.predicate_select({},:class =>'form-control') %>	
  </div>
  
  <%= f.value_fields do |v| %>
  	<div class="row col-md-4">
    	<%= v.text_field :value, :class => 'form-control' %>
	</div>
  <% end %>
  <h4><%= link_to "remove", '#', class: "remove_fields" %></h4><br/></div>

app/views/clients/admin.html.erb
<h1>Admin Page</h1>

<div class="container">
        <div class="col-md-12">
            <div class="well well-lg">
            <h3>Search parameters</h3>

<%= search_form_for @search, url: search_payments_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
    <div class="field">
    </div>
    <div id="child-left">
    <h4><p><%= link_to_add_fields "Add Conditions", f, :condition%></p></h4>  
    </div>
    
    <div>
      <h4>Sort:</h4> 
    </div>
     
    <%= f.sort_fields do |s| %>
    <div class="row">
    <div class="col-md-4">
      <%= s.sort_select({}, :class => 'form-control') %>
      <br />
     <div class="actions"><%= f.submit "Search", :class => 'btn btn-primary' %></div>
    </div>
    
    <% end %>
    </div>
    
<% end %>
</div>
</div>
</div>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
<table id="payments" class="table table-striped table-bordered">
  <tr>
    <th>Client Name</th>
    <th>Defendent Name</th>
    <th>Citation Number</th>
    <th>Email</th>
    <th>Address</th>
    <th>Phone Number</th>
    <th>Amount</th>
    <th>Convenience Fee</th>
    <th>Total Amount</th>
  </tr>
<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.client.name %></td>
    <td><%= payment.defendent_name %></td>
    <td><%= payment.citation_number %></td>
    <td><%= payment.email %></td>
    <td><%= payment.address %></td>
    <td><%= payment.phone_number %></td>
    <td><%= number_to_currency(payment.amount) %></td>
    <td><%= number_to_currency(payment.convenience_fee) %></td>
    <td><%= number_to_currency(payment.total_amount) %></td>
  </tr>
<% end %>
</table>
</div>
</div>
</div>
</div>

app/views/clients/index.html.erb
<h1>Clients on this Server</h1>

<ul>
	<% @clients.each do |client| %>
		<li><%= link_to client.name, root_url(subdomain: client.subdomain) %></li>
	<% end %>
</ul>

app/views/clients/show.html.erb
<h1><%= @client.name %></h1>

<h3 align="center"> Payment Form</h3>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
               <form class="form-horizontal" method= post onsubmit=" return validateForm(event)" action="https://www.bridgepaynetsecuretest.com/WebLink3/WebLink.aspx">
<fieldset>

<!-- Form Name -->
<legend>Citation</legend>
<input type="hidden" name="mode" value="PaymentForm" />
 <input type="hidden" name="login" value="emvpgtest" />
 <input type="hidden" name="ReceiptURL" value="http://ruleville.lvh.me:3000/success" /> 
  <input type="hidden" name="Style_Page_BackgroundColor" value="#A9A9A9" />
 <input type="hidden" name="Style_Form_BackgroundColor" value="#D3D3D3" />
 <input type="hidden" name="Style_FontFamily" value="’Times New Roman’" /> 
 <input type="hidden" name="password" value="QAZ123wsx!@#" />
<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="defendantName">Defendent Name</label>  
  <div class="col-md-4">
  <input id="defendantName" name="defendantName" type="text" placeholder="Defendent Name" class="form-control input-md" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="citationNo">Citation number</label>  
  <div class="col-md-4">
  <input id="citationNo" name="citationNo" type="text" placeholder="Citation Number" class="form-control input-md" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="email">Email</label>  
  <div class="col-md-4">
  <input id="email" name="email" type="text" placeholder="Email" class="form-control input-md" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="address">Address</label>  
  <div class="col-md-6">
  <input id="address" name="address" type="text" placeholder="Address" class="form-control input-md" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="phoneNumber">Phone Number</label>  
  <div class="col-md-4">
  <input id="phoneNumber" name="phoneNumber" type="text" onkeypress='validatePhoneNumber(event)' placeholder="###-###-####" class="form-control input-md" maxlength="12" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="amount">Amount ($)</label>  
  <div class="col-md-4">
  <input id="amount" name="amount" onkeypress='validate(event)' onkeyup='updateAmounts()' type="text" placeholder="Amount" class="form-control input-md" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="convenienceFee">Convenience Fee ($)</label>  
  <div class="col-md-4">
  <input id="convenienceFee" name="convenienceFee" type="text" readonly="readonly" placeholder="Convenience Fee" class="form-control input-md" step='0.01' required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="TotalAmt">Total Amount ($)</label>  
  <div class="col-md-4">
  <input  type="text" name="TotalAmt" id="TotalAmt" readonly="readonly" placeholder="Total Amount" class="form-control input-md" step='0.01' required="">
    
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="singlebutton">Submit Payment</label>
  <div class="col-md-4">
  <input type="submit" value="Submit payment" id="singlebutton" class="btn btn-primary"  />
  </div>
</div>

</fieldset>
</form>
            </div>
        </div>
    </div>
</div>

app/views/clients/success.html.erb
<h3 align="center"> Successful Payment</h3>

<div class="container">
    <div class="row">
        <div class="col-md-12" style="margin-left: 20%; width: 60%; border: 3px solid #808080; padding: 10px; }">
            <div class="well well-sm">
            	<h4>Defendent Name</h4> 
				<h5> <%= @defendentName %></h5>
				<h4> Citation Number </h4>
				<h5><%= @citationNumber %></h5>
				<h4>Address</h4>
				<h5><%= @address %></h5>
				<h4>Phone Number</h4>
				<h5><%= @phoneNumber %></h5>
				<h4>Email</h4>
				<h5><%= @email %></h5>
				<h4>Amount Paid</h4>
				<h5><%= @amount %>$</h5>
				<h4>Convenience Fee Paid</h4>
				<h5><%= @convenienceFee %>$</h5>
				<h4>Total Amount Paid</h4>
				<h5><%= @TotalAmt %>$</h5>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
   <nav class = "navbar navbar-default" role = "navigation">
   
   <div class = "navbar-header">
      <a class = "navbar-brand" href = "<%= root_url(:subdomain => 'www') %>">Payment Services</a>
   </div>
   
	</nav>
  <body>
    <%= yield %>
  </body>
</html>